version: '3'
services:
  pg_db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=movies
    expose:
      - "5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./sql/movies_schema_dump.sql:/docker-entrypoint-initdb.d/movies_schema_dump.sql
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  backend:
    build:
      context: .
    expose:
      - "8000"
    depends_on:
      - pg_db
  webserver:
    image: nginx:1.19.2
    ports:
      - 80:80
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./host_volume:/data
    depends_on:
      - backend
volumes: 
  media: 
