# Generated by Django 3.1 on 2021-06-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genre',
            name='unique genre name',
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='movies_pers_name_64a075_idx'),
        ),
    ]
